from tokenize import String
from typing import List


class FetchEventSeries:
    def get_bard_event_series(self) -> List[str]:
        """
        We fetch some example workshop and conference series from CEUR-WS as generated by BARD
        and use them in our matcher.
        BARD query - conference series from ceur-ws that are not present in wikidata
                   - workshop series from ceur-ws that are not present in wikidata
        :return: list of strings
        """
        workshop_series = [
            "Agent-based Modeling and Policy-Making (AMPM)",
            "Computational Linguistics and Intelligent Systems (CLINS)",
            "EICS Series",
            "Games and Learning (GaL)",
            "Federated Learning and Analytics (FedAnal)",
        ]

        conference_series = [
            "ECML-PKDD",
            "Data Science for Social Good (D4SG)",
            "International Conference on Semantic Computing (ICSC)",
            "International Conference on Social Informatics (SocInfo)",
            "International Conference on Web Intelligence (WI)",
            "Semantic Web for Health Care and Life Sciences (ESWC-Health)",
        ]

        event_series = workshop_series + conference_series
        return event_series
